const cars = [
  { id: 1, name: "Alfa Romeo Brera", image: "https://static.wikia.nocookie.net/nfs/images/9/91/NFSC_AlfaRomeo_Brera_Stock.jpg/revision/latest/scale-to-width-down/114?cb=20220328173856&path-prefix=en" },  
  { id: 2, name: "Aston Martin DB9", image: "https://static.wikia.nocookie.net/nfs/images/a/a5/NFSC_AstonMartin_DB9_Stock.jpg/revision/latest/scale-to-width-down/114?cb=20220328173920&path-prefix=en" },
  { id: 3, name: "Chevrolet Camaro SS", image: "https://static.wikia.nocookie.net/nfs/images/3/34/NFSC_Chevrolet_CamaroSS_Stock.jpg/revision/latest/scale-to-width-down/114?cb=20220328174110&path-prefix=en" },
  { id: 4, name: "Chevrolet Corvette Z06", image: "https://static.wikia.nocookie.net/nfs/images/d/dc/NFSC_Chevrolet_CorvetteZ06_Stock.jpg/revision/latest/scale-to-width-down/114?cb=20220328174245&path-prefix=en" },
  { id: 5, name: "Chrysler 300C HEMI SRT8", image: "https://static.wikia.nocookie.net/nfs/images/b/bf/NFSC_Chrysler_300CHemiSRT8_Stock.jpg/revision/latest/scale-to-width-down/114?cb=20220328174336&path-prefix=en" },
  { id: 6, name: "Dodge Challenger Concept", image: "https://static.wikia.nocookie.net/nfs/images/9/98/NFSC_Dodge_ChallengerConcept_Stock.jpg/revision/latest/scale-to-width-down/114?cb=20220328174356&path-prefix=en" },
  { id: 7, name: "Dodge Challenger R/T", image: "https://static.wikia.nocookie.net/nfs/images/9/96/NFSC_Dodge_ChallengerRT_Stock.jpg/revision/latest/scale-to-width-down/114?cb=20220328174403&path-prefix=en" },
  { id: 8, name: "Dodge Charger R/T", image: "https://static.wikia.nocookie.net/nfs/images/5/59/NFSC_Dodge_ChargerRT_Stock.jpg/revision/latest/scale-to-width-down/114?cb=20220328174435&path-prefix=en" },
  { id: 9, name: "Dodge Charger SRT8", image: "https://static.wikia.nocookie.net/nfs/images/8/8b/NFSC_Dodge_ChargerSRT8_Stock.jpg/revision/latest/scale-to-width-down/114?cb=20220328174507&path-prefix=en" },
  { id: 10, name: "Dodge Viper SRT10", image: "https://static.wikia.nocookie.net/nfs/images/0/0f/NFSC_Dodge_ViperSRT10_Stock.jpg/revision/latest/scale-to-width-down/114?cb=20220328174514&path-prefix=en" },
  { id: 11, name: "Ford GT", image: "https://static.wikia.nocookie.net/nfs/images/5/5a/NFSC_Ford_GT_Stock.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 12, name: "Ford Mustang GT", image: "https://static.wikia.nocookie.net/nfs/images/0/0b/NFSC_Ford_MustangGT_Stock.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 13, name: "Infiniti G35", image: "https://static.wikia.nocookie.net/nfs/images/0/0c/NFSC_Infiniti_G35_Stock.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 14, name: "Jaguar XK", image: "https://static.wikia.nocookie.net/nfs/images/4/4d/NFSC_Jaguar_XK_Stock.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 15, name: "Lamborghini Gallardo", image: "https://static.wikia.nocookie.net/nfs/images/4/4f/NFSC_Lamborghini_Gallardo_Stock.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 16, name: "Lamborghini Murciélago", image: "https://static.wikia.nocookie.net/nfs/images/9/9e/NFSC_Lamborghini_Murcielago_Stock.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 17, name: "Lotus Elise", image: "https://static.wikia.nocookie.net/nfs/images/3/3a/NFSC_Lotus_Elise_Stock.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 18, name: "Mazda Mazdaspeed3", image: "https://static.wikia.nocookie.net/nfs/images/2/2e/NFSC_Mazda_Mazdaspeed3_Stock.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 19, name: "Mazda RX-7", image: "https://static.wikia.nocookie.net/nfs/images/7/7d/NFSC_Mazda_RX7_Stock.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 20, name: "Mazda RX-8", image: "https://static.wikia.nocookie.net/nfs/images/3/3a/NFSC_Mazda_RX8_Stock.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 21, name: "Mercedes-Benz CLK 500", image: "https://static.wikia.nocookie.net/nfs/images/4/4f/NFSC_MercedesBenz_CLK500_Stock.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 22, name: "Mercedes-Benz SL65 AMG", image: "https://static.wikia.nocookie.net/nfs/images/4/4a/NFSC_MercedesBenz_SL65AMG_Stock.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 23, name: "Mercedes-Benz SLR McLaren", image: "https://static.wikia.nocookie.net/nfs/images/9/9e/NFSC_MercedesBenz_SLRMcLaren_Stock.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 24, name: "Mitsubishi Eclipse GT", image: "https://static.wikia.nocookie.net/nfs/images/8/8d/NFSC_Mitsubishi_EclipseGT_Stock.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 25, name: "Mitsubishi Lancer Evolution IX", image: "https://static.wikia.nocookie.net/nfs/images/8/8a/NFSC_Mitsubishi_LancerEvolutionIX_Stock.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 26, name: "Nissan 240SX", image: "https://static.wikia.nocookie.net/nfs/images/8/8c/NFSC_Nissan_240SX_Stock.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 27, name: "Nissan 350Z", image: "https://static.wikia.nocookie.net/nfs/images/8/8e/NFSC_Nissan_350Z_Stock.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 28, name: "Nissan Skyline GT-R", image: "https://static.wikia.nocookie.net/nfs/images/4/4f/NFSC_Nissan_SkylineGTR_Stock.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 29, name: "Plymouth HEMI 'Cuda", image: "https://static.wikia.nocookie.net/nfs/images/3/3a/NFSC_Plymouth_HemiCuda_Stock.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 30, name: "Porsche 911 Turbo", image: "https://static.wikia.nocookie.net/nfs/images/4/4e/NFSC_Porsche_911Turbo_Stock.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 31, name: "Porsche Carrera GT", image: "https://static.wikia.nocookie.net/nfs/images/2/2f/NFSC_Porsche_CarreraGT_Stock.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 32, name: "Porsche Cayman S", image: "https://static.wikia.nocookie.net/nfs/images/0/0a/NFSC_Porsche_CaymanS_Stock.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 33, name: "Renault Clio V6", image: "https://static.wikia.nocookie.net/nfs/images/5/5e/NFSC_Renault_ClioV6_Stock.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 34, name: "Shelby GT500", image: "https://static.wikia.nocookie.net/nfs/images/5/5f/NFSC_Shelby_GT500_Stock.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 35, name: "Subaru Impreza WRX STI", image: "https://static.wikia.nocookie.net/nfs/images/7/7b/NFSC_Subaru_WRXSTI_Stock.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 36, name: "Toyota Supra", image: "https://static.wikia.nocookie.net/nfs/images/1/1c/NFSC_Toyota_Supra_Stock.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 37, name: "Vauxhall Monaro VXR", image: "https://static.wikia.nocookie.net/nfs/images/3/3c/NFSC_Vauxhall_MonaroVXR_Stock.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 38, name: "Volkswagen Golf R32", image: "https://static.wikia.nocookie.net/nfs/images/7/7a/NFSC_Volkswagen_GolfR32_Stock.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 39, name: "Aston Martin DB9 (Custom)", image: "https://static.wikia.nocookie.net/nfs/images/4/4e/NFSC_AstonMartin_DB9_Custom.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 40, name: "Chevrolet Camaro SS (Custom)", image: "https://static.wikia.nocookie.net/nfs/images/4/4a/NFSC_Chevrolet_CamaroSS_Custom.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 41, name: "Chevrolet Corvette Z06 (Custom)", image: "https://static.wikia.nocookie.net/nfs/images/8/8e/NFSC_Chevrolet_CorvetteZ06_Custom.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 42, name: "Dodge Challenger Concept (Custom)", image: "https://static.wikia.nocookie.net/nfs/images/8/8c/NFSC_Dodge_ChallengerConcept_Custom.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 43, name: "Dodge Charger R/T (Custom)", image: "https://static.wikia.nocookie.net/nfs/images/3/3c/NFSC_Dodge_ChargerRT_Custom.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 44, name: "Dodge Viper SRT10 (Custom)", image: "https://static.wikia.nocookie.net/nfs/images/4/4f/NFSC_Dodge_ViperSRT10_Custom.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 45, name: "Ford GT (Custom)", image: "https://static.wikia.nocookie.net/nfs/images/5/5a/NFSC_Ford_GT_Custom.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 46, name: "Ford Mustang GT (Custom)", image: "https://static.wikia.nocookie.net/nfs/images/0/0b/NFSC_Ford_MustangGT_Custom.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 47, name: "Jaguar XK (Custom)", image: "https://static.wikia.nocookie.net/nfs/images/4/4d/NFSC_Jaguar_XK_Custom.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 48, name: "Lamborghini Gallardo (Custom)", image: "https://static.wikia.nocookie.net/nfs/images/4/4f/NFSC_Lamborghini_Gallardo_Custom.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 49, name: "Lamborghini Murciélago (Custom)", image: "https://static.wikia.nocookie.net/nfs/images/9/9e/NFSC_Lamborghini_Murcielago_Custom.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 50, name: "Lotus Elise (Custom)", image: "https://static.wikia.nocookie.net/nfs/images/3/3a/NFSC_Lotus_Elise_Custom.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 51, name: "Mazda RX-7 (Custom)", image: "https://static.wikia.nocookie.net/nfs/images/7/7d/NFSC_Mazda_RX7_Custom.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 52, name: "Mazda RX-8 (Custom)", image: "https://static.wikia.nocookie.net/nfs/images/3/3a/NFSC_Mazda_RX8_Custom.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 53, name: "Mercedes-Benz CLK 500 (Custom)", image: "https://static.wikia.nocookie.net/nfs/images/4/4f/NFSC_MercedesBenz_CLK500_Custom.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 54, name: "Mercedes-Benz SL65 AMG (Custom)", image: "https://static.wikia.nocookie.net/nfs/images/4/4a/NFSC_MercedesBenz_SL65AMG_Custom.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 55, name: "Mitsubishi Eclipse GT (Custom)", image: "https://static.wikia.nocookie.net/nfs/images/8/8d/NFSC_Mitsubishi_EclipseGT_Custom.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 56, name: "Mitsubishi Lancer Evolution IX (Custom)", image: "https://static.wikia.nocookie.net/nfs/images/8/8a/NFSC_Mitsubishi_LancerEvolutionIX_Custom.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 57, name: "Nissan 240SX (Custom)", image: "https://static.wikia.nocookie.net/nfs/images/8/8c/NFSC_Nissan_240SX_Custom.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 58, name: "Nissan 350Z (Custom)", image: "https://static.wikia.nocookie.net/nfs/images/8/8e/NFSC_Nissan_350Z_Custom.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 59, name: "Nissan Skyline GT-R (Custom)", image: "https://static.wikia.nocookie.net/nfs/images/4/4f/NFSC_Nissan_SkylineGTR_Custom.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 60, name: "Plymouth HEMI 'Cuda (Custom)", image: "https://static.wikia.nocookie.net/nfs/images/3/3a/NFSC_Plymouth_HemiCuda_Custom.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 61, name: "Porsche 911 Turbo (Custom)", image: "https://static.wikia.nocookie.net/nfs/images/4/4e/NFSC_Porsche_911Turbo_Custom.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 62, name: "Porsche Carrera GT (Custom)", image: "https://static.wikia.nocookie.net/nfs/images/2/2f/NFSC_Porsche_CarreraGT_Custom.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 63, name: "Porsche Cayman S (Custom)", image: "https://static.wikia.nocookie.net/nfs/images/0/0a/NFSC_Porsche_CaymanS_Custom.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 64, name: "Renault Clio V6 (Custom)", image: "https://static.wikia.nocookie.net/nfs/images/5/5e/NFSC_Renault_ClioV6_Custom.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 65, name: "Shelby GT500 (Custom)", image: "https://static.wikia.nocookie.net/nfs/images/5/5f/NFSC_Shelby_GT500_Custom.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 66, name: "Subaru Impreza WRX STI (Custom)", image: "https://static.wikia.nocookie.net/nfs/images/7/7b/NFSC_Subaru_WRXSTI_Custom.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 67, name: "Toyota Supra (Custom)", image: "https://static.wikia.nocookie.net/nfs/images/1/1c/NFSC_Toyota_Supra_Custom.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 68, name: "Vauxhall Monaro VXR (Custom)", image: "https://static.wikia.nocookie.net/nfs/images/3/3c/NFSC_Vauxhall_MonaroVXR_Custom.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 69, name: "Volkswagen Golf R32 (Custom)", image: "https://static.wikia.nocookie.net/nfs/images/7/7a/NFSC_Volkswagen_GolfR32_Custom.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 70, name: "Audi Le Mans Quattro", image: "https://static.wikia.nocookie.net/nfs/images/4/4e/NFSC_Audi_LeMansQuattro_Stock.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 71, name: "Chevrolet Chevelle SS", image: "https://static.wikia.nocookie.net/nfs/images/8/8e/NFSC_Chevrolet_ChevelleSS_Stock.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 72, name: "Dodge Charger 1969", image: "https://static.wikia.nocookie.net/nfs/images/3/3c/NFSC_Dodge_Charger1969_Stock.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 73, name: "Ford Mustang GT (1967)", image: "https://static.wikia.nocookie.net/nfs/images/0/0b/NFSC_Ford_MustangGT67_Stock.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 74, name: "Koenigsegg CCX", image: "https://static.wikia.nocookie.net/nfs/images/4/4e/NFSC_Koenigsegg_CCX_Stock.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 75, name: "Mazda RX-8 (Apex)", image: "https://static.wikia.nocookie.net/nfs/images/3/3a/NFSC_Mazda_RX8_Apex.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 76, name: "Mazda RX-7 (Apex)", image: "https://static.wikia.nocookie.net/nfs/images/7/7d/NFSC_Mazda_RX7_Apex.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 77, name: "Nissan 240SX (Apex)", image: "https://static.wikia.nocookie.net/nfs/images/8/8c/NFSC_Nissan_240SX_Apex.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 78, name: "Nissan 350Z (Apex)", image: "https://static.wikia.nocookie.net/nfs/images/8/8e/NFSC_Nissan_350Z_Apex.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 79, name: "Nissan Skyline GT-R (Apex)", image: "https://static.wikia.nocookie.net/nfs/images/4/4f/NFSC_Nissan_SkylineGTR_Apex.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 80, name: "Porsche 911 Turbo (Apex)", image: "https://static.wikia.nocookie.net/nfs/images/4/4e/NFSC_Porsche_911Turbo_Apex.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 81, name: "Porsche Carrera GT (Apex)", image: "https://static.wikia.nocookie.net/nfs/images/2/2f/NFSC_Porsche_CarreraGT_Apex.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 82, name: "Porsche Cayman S (Apex)", image: "https://static.wikia.nocookie.net/nfs/images/0/0a/NFSC_Porsche_CaymanS_Apex.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 83, name: "Subaru Impreza WRX STI (Apex)", image: "https://static.wikia.nocookie.net/nfs/images/7/7b/NFSC_Subaru_WRXSTI_Apex.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" },
  { id: 84, name: "Toyota Supra (Apex)", image: "https://static.wikia.nocookie.net/nfs/images/1/1c/NFSC_Toyota_Supra_Apex.jpg/revision/latest/scale-to-width-down/256?path-prefix=en" }
]

export default cars